version: "3"
volumes:
  data:
services:
  postgres-sql-eval:
    image: docker.io/postgres:16-alpine
    container_name: pg-timetable
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data
