package com.patrick.timetableappbackend.model;

public enum Year {
    FIRST,SECOND,THIRD,FOURTH,FIFTH,SIXTH, SEVENTH, EIGHTH,
    NINTH, TENTH, ELEVENTH, TWELVETH, PREPARATORY, SMALL_GROUP,
    MIDDLE_GROUP, SENIOR_GROUP
}
